/**
 * A complete fake candidate, for test builds only.
 *
 * Testing the apply agent used to require the whole upstream chain: sign into
 * the web app, sync a profile, optimise a CV so a tailored PDF exists, then
 * launch a batch — several minutes of setup before the agent does the one thing
 * under test, and every ATS bug found that way cost the same setup again. This
 * module lets `npm run build:test` produce a bundle that seeds itself.
 *
 * A normal build never reads this file: build.mjs resolves the import to
 * fixtures/noop.js instead, so the fake candidate is absent from the production
 * bundle by construction rather than by dead-code elimination (noop.js explains
 * why that distinction turned out to matter).
 *
 * Three rules this file keeps:
 *
 *   1. It NEVER overwrites real data. Seeding fills empty storage slots only, so
 *      loading a test build over a signed-in profile changes nothing.
 *   2. Every value is recognisably fake at a glance — @example.invalid is a
 *      reserved TLD that cannot resolve, and the name says TEST. A screenshot of
 *      a form filled from here should be impossible to mistake for a real
 *      application.
 *   3. The values are the ones REAL forms demand, not a minimal stub: the gaps
 *      measured on Mondelez (postal code, notice period, GPA, work
 *      authorisation, sponsorship, expected salary) are all populated, because a
 *      fixture that leaves them blank cannot exercise the steps they block.
 */

import { FIXTURE_CREDENTIALS, FIXTURE_CREDENTIAL_MODE } from './creds.local.js';
import { pickCredential } from './pick.js';

/** Flat profile — mirrors ExtensionProfile in frontend/src/lib/extension-profile.ts. */
export const DUMMY_PROFILE = {
    fullName: 'TEST Nguyen Van A',
    firstName: 'A',
    middleName: 'Van',
    lastName: 'TEST Nguyen Van',
    email: 'copo.agent.test@example.invalid',
    phone: '0900000001',
    dateOfBirth: '1996-01-15',
    // Gender is NOT a demographic answer here — it is what the Prefix ladder
    // reads to choose Mr./Ms., and PwC renders "Prefix*" REQUIRED. The EEO
    // decline path stays exercised by race / veteran / disability, which this
    // profile deliberately leaves empty.
    gender: 'Nam',
    // Administrative fact on VN tenants, and the one demographic a VN candidate
    // answers rather than declines (see the ethnicity rule in answers.js).
    ethnicity: 'Kinh',
    nationality: 'Vietnamese',         // must resolve to a decline option, not a value
    maritalStatus: '',
    addressProvince: 'Hà Nội',
    addressDistrict: 'Cầu Giấy',
    addressStreet: '1 Duy Tan Street',
    addressStreet2: '',
    driversLicense: 'Yes',
    postalCode: '100000',
    currentTitle: 'Product Owner',
    currentLevel: 'Middle',
    yearsOfExperience: 4,
    highestDegree: 'Bachelor',
    // Workday asks "Overall Result (GPA)" REQUIRED on some tenants and answers it
    // ONLY from this key — no résumé parse supplies it and a plausible number
    // would be a fabricated academic record.
    gpa: '4.0',
    noticePeriod: '30 days',
    availableStartDate: '',   // empty on purpose: derives from the notice period
    workAuthorized: 'Yes',
    requiresSponsorship: 'No',
    currentSalary: '',
    currentIndustry: 'Technology',
    currentFields: 'Product Management',
    desiredLocations: 'Hà Nội, Hồ Chí Minh',
    desiredSalary: '25,000,000 - 30,000,000 VND',
    coverLetter: 'This is an automated TEST application generated by a Copo test '
        + 'build. It is not a real application from a real candidate.',
    applyMessage: 'TEST message to the hiring team, generated by a Copo test build. '
        + 'It is not a real application from a real candidate.',
    skills: 'Product Management, Roadmapping, SQL, Figma, Agile, Data Analysis',
};

/** Structured CV — mirrors CVData in frontend/src/lib/types.ts. */
export const DUMMY_CV = {
    name: 'TEST Nguyen Van A',
    summary: 'Product Owner with 4 years building B2B SaaS. TEST DATA — not a real person.',
    desired_job_title: 'Product Owner',
    skills: ['Product Management', 'Roadmapping', 'SQL', 'Figma', 'Agile', 'Data Analysis'],
    experience: [
        {
            title: 'Product Owner',
            company: 'Example Software JSC',
            duration_months: 26,
            start_date: '03/2024',
            end_date: 'Hiện tại',
            description: 'Owned the billing product. Ran discovery, wrote specs, shipped '
                + 'fortnightly with a team of six.',
        },
        {
            title: 'Business Analyst',
            company: 'Example Consulting Co',
            duration_months: 22,
            start_date: '05/2022',
            end_date: '02/2024',
            description: 'Gathered requirements and mapped processes for ERP rollouts.',
        },
    ],
    education: [
        {
            degree: 'Marketing',
            institution: 'Example National University',
            year: '2022',
            // Required on Workday's My Experience and knowable only to the
            // candidate — the exact field that stalled a real run.
            gpa: '3.2',
        },
    ],
    projects: [],
    certifications: [{ name: 'Professional Scrum Product Owner I', issuer: 'Scrum.org', year: '2023' }],
    languages: [
        { language: 'Vietnamese', level: 'Native' },
        { language: 'English', level: 'Fluent' },
    ],
    awards: [],
    activities: [],
    contact: {
        email: 'copo.agent.test@example.invalid',
        phone: '0900000001',
        address_province: 'Hà Nội',
        address_district: 'Cầu Giấy',
        address_street: '1 Duy Tan Street',
        address_postal_code: '100000',
        linkedin: '',
        github: '',
        portfolio: '',
    },
    personal: {
        date_of_birth: '1996-01-15',
        gender: '',
        nationality: 'Vietnamese',
        marital_status: '',
    },
    employment: {
        current_title: 'Product Owner',
        current_company: 'Example Software JSC',
        current_level: 'Middle',
        current_industry: 'Technology',
        current_fields: 'Product Management',
        current_salary: '',
        years_of_experience: 4,
        highest_degree: 'Bachelor',
    },
    preferences: {
        desired_locations: 'Hà Nội, Hồ Chí Minh',
        desired_salary: '25,000,000 - 30,000,000 VND',
        notice_period: '30 days',
        work_authorized: 'Yes',
        requires_sponsorship: 'No',
    },
};

export const DUMMY_CV_FILENAME = 'TEST_CANDIDATE_DO_NOT_SUBMIT.pdf';

/**
 * The lines the generated PDF carries.
 *
 * ASCII only: the PDF below writes text in Helvetica/WinAnsi, where Vietnamese
 * diacritics come out as mojibake — which is worse than plain text for the one
 * thing this document exists to feed, an ATS résumé parser.
 */
const PDF_LINES = [
    'TEST CANDIDATE - AUTOMATED TEST DATA - DO NOT SUBMIT',
    '',
    'TEST Nguyen Van A',
    'Product Owner',
    'copo.agent.test@example.invalid | 0900000001',
    '1 Duy Tan Street, Cau Giay, Ha Noi, 100000, Vietnam',
    '',
    'SUMMARY',
    'Product Owner with 4 years building B2B SaaS. This document is synthetic',
    'test data generated by a Copo test build. It describes no real person.',
    '',
    'EXPERIENCE',
    'Product Owner - Example Software JSC (03/2024 - Present)',
    'Owned the billing product. Ran discovery, wrote specs, shipped fortnightly.',
    'Business Analyst - Example Consulting Co (05/2022 - 02/2024)',
    'Gathered requirements and mapped processes for ERP rollouts.',
    '',
    'EDUCATION',
    'Example National University - Marketing (2022) - GPA 3.2',
    '',
    'LANGUAGES',
    'Vietnamese (Native), English (Fluent)',
    '',
    'SKILLS',
    'Product Management, Roadmapping, SQL, Figma, Agile, Data Analysis',
];

/** Escape a string for a PDF literal — backslash, then the two paren delimiters. */
const pdfEscape = (s) => s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');

/**
 * Build a one-page PDF as base64.
 *
 * Generated rather than embedded so no real person's CV has to live in the repo
 * to make testing work, and so the file stays a few kB instead of bloating every
 * bundle with a base64 blob.
 *
 * The xref table stores each object's BYTE offset, so offsets are measured on
 * the bytes rather than the string: the header text is ASCII, but that is a
 * property worth not depending on silently.
 */
export function buildDummyPdfBase64() {
    const text = PDF_LINES.map(l => `(${pdfEscape(l)}) Tj T*`).join('\n');
    const stream = `BT\n/F1 10 Tf\n50 790 Td\n14 TL\n${text}\nET`;

    const objects = [
        '<< /Type /Catalog /Pages 2 0 R >>',
        '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] '
            + '/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
        '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
        `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    ];

    let pdf = '%PDF-1.4\n';
    const offsets = [];
    objects.forEach((body, i) => {
        offsets.push(pdf.length);
        pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
    });

    const xrefAt = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    for (const off of offsets) pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
    pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`
        + `startxref\n${xrefAt}\n%%EOF`;

    // btoa needs one byte per char; the PDF above is ASCII by construction, and
    // charCodeAt & 0xff would silently corrupt anything that was not.
    let bin = '';
    for (let i = 0; i < pdf.length; i++) bin += String.fromCharCode(pdf.charCodeAt(i) & 0xff);
    return btoa(bin);
}

/** The storage slots the agent reads to know who it is applying as. */
export const SEED_KEYS = ['jobfitProfile', 'jobfitCv', 'cvFileBase64', 'cvFileName'];

/**
 * Fill any empty storage slot the agent reads, and report what was filled.
 *
 * Returns the list of keys seeded so the caller can log it — a test build that
 * seeds nothing (because real data is already there) looks identical to one that
 * seeded everything, and that difference is exactly what you want to know when
 * the agent then fills a form with someone's actual name.
 */
export async function seedDummyData() {
    if (typeof chrome === 'undefined' || !chrome?.storage?.local) return [];
    const KEYS = SEED_KEYS;
    const have = await chrome.storage.local.get(KEYS);
    const patch = {};

    if (!have.jobfitProfile) patch.jobfitProfile = DUMMY_PROFILE;
    if (!have.jobfitCv) { patch.jobfitCv = DUMMY_CV; patch.jobfitCvSyncedAt = Date.now(); }
    if (!have.cvFileBase64 || !have.cvFileName) {
        patch.cvFileBase64 = buildDummyPdfBase64();
        patch.cvFileName = DUMMY_CV_FILENAME;
    }

    const seeded = Object.keys(patch).filter(k => KEYS.includes(k));
    if (seeded.length) await chrome.storage.local.set(patch);
    return seeded;
}

/**
 * The storage key a test build reads an ATS login out of.
 *
 * Production has no such key and must not grow one. Credentials there are
 * fetched from the backend per tenant, at the moment of use, and live only in
 * the content script's local scope for the length of the fill — a password in
 * chrome.storage.local is readable by anything that can reach the extension's
 * storage and outlives the apply by however long nobody clears it. This exists
 * because testing against a real ATS otherwise needs the whole backend
 * credential path stood up, and it is confined to fixture builds by the same
 * module swap that hides the fake candidate.
 */
export const CREDENTIAL_KEY = 'jobfitApplyCredentials';

/**
 * Read the test login, if one was supplied.
 *
 * Shape: `{ email, password }`, optionally `{ operation: 'signup' }` to probe an
 * account that does not exist yet. Set it from the service-worker console:
 *
 *   chrome.storage.local.set({ jobfitApplyCredentials: { email: '…', password: '…' } })
 *
 * One credential covers every tenant. That is wrong for a real batch across
 * several companies and exactly right for driving one ATS by hand, which is what
 * this is for.
 */
export async function readFixtureCredential() {
    let stored = null;
    if (typeof chrome !== 'undefined' && chrome?.storage?.local) {
        const got = await chrome.storage.local.get(CREDENTIAL_KEY);
        stored = got?.[CREDENTIAL_KEY] ?? null;
    }
    return pickCredential(stored, FIXTURE_CREDENTIALS, FIXTURE_CREDENTIAL_MODE);
}

/** Replace whatever is in the four slots with the fixture. */
export async function installDummyData() {
    if (typeof chrome === 'undefined' || !chrome?.storage?.local) return [];
    await chrome.storage.local.remove(SEED_KEYS);
    return seedDummyData();
}

/** Empty the four slots so the web app can sync the real profile back in. */
export async function clearDummyData() {
    if (typeof chrome === 'undefined' || !chrome?.storage?.local) return;
    await chrome.storage.local.remove(SEED_KEYS);
}

/**
 * Throw away the persisted batch + per-tenant auth state.
 *
 * The attempt budget is 1 signup + 1 login per tenant per batch, and it is
 * persisted so an MV3 worker restart cannot hand out a second one. Testing burns
 * through that constantly — every abandoned run leaves a tenant with nothing
 * left, and the next attempt refuses before touching the page. Production
 * discards a dead batch on its own now; this is the manual version, for when you
 * want a clean budget without waiting or reloading.
 */
export async function resetAtsRuntime() {
    if (typeof chrome === 'undefined' || !chrome?.storage?.local) return;
    await chrome.storage.local.remove([
        'atsRuntime', 'applyQueue', 'isProcessing', 'currentJobIndex',
        'currentTabId', 'jobStartedAt', 'lastHeartbeatAt', 'applySession',
    ]);
}

const BANNER = '[Copo] ⚠️  FIXTURE BUILD — this extension carries FAKE candidate data. '
    + 'Never use it to send a real application.';

/**
 * Wire the fixture up.
 *
 * INSTALLING the extension overwrites; a plain worker wake does not. That split
 * is the whole ergonomics of this thing. Seeding empty slots only was the safe
 * design and it was also useless: anyone who has ever signed into the web app
 * has a profile in storage, so loading a test build seeded nothing and they
 * tested with their real identity — the exact outcome the caution was meant to
 * prevent. Building and loading a fixture build IS the instruction to use fake
 * data, so onInstalled acts on it. A worker wake is not a new instruction, so it
 * only fills what is missing and leaves a forced state alone.
 *
 * The console banner fires on every wake regardless. A fixture build behaves
 * exactly like a real one right up until it types a stranger's name into a real
 * employer's form, so that line is the only thing telling them apart before that
 * point — the data is the second line of defence (the name says TEST, the CV file
 * says DO NOT SUBMIT, and both appear in the form).
 */
export function initFixture() {
    const announce = (seeded) => console.warn(BANNER
        + (seeded.length ? ` Seeded: ${seeded.join(', ')}.` : ' Slots already filled; seeded nothing.')
        + ' — copoFixture.install() to re-apply, copoFixture.clear() to remove it.');

    // Fires when the unpacked extension is loaded or reloaded: the moment the
    // user actually chose this build.
    try {
        chrome.runtime.onInstalled.addListener(() => {
            // Budget too, not just the data. A test build inheriting the spent
            // login attempts of whatever ran before it refuses at the first login
            // wall, and reports it as though the company were the problem.
            Promise.all([installDummyData(), resetAtsRuntime()])
                .then(([seeded]) => console.warn(
                    `${BANNER} Installed over any previous data: ${seeded.join(', ')}. ATS budget reset.`))
                .catch(e => console.warn('[Copo] fixture install failed:', e?.message));
        });
    } catch { /* no runtime here — nothing to hook */ }

    seedDummyData().then(announce).catch(e => console.warn('[Copo] fixture seed failed:', e?.message));

    self.copoFixture = {
        /** Overwrite the slots with the fixture, whatever is in them now. */
        install: async () => {
            const keys = await installDummyData();
            await resetAtsRuntime();
            console.warn('[Copo] fixture installed:', keys.join(', '), '— ATS attempt budget reset.');
            return keys;
        },
        /** Remove it. Re-sync from the web app to get the real profile back. */
        clear: async () => {
            await clearDummyData();
            console.warn('[Copo] fixture cleared — re-sync from the web app to restore real data.');
        },
        /** Give every tenant its login attempts back. */
        resetAts: async () => {
            await resetAtsRuntime();
            console.warn('[Copo] ATS attempt budget + batch state cleared. Reload the page to retry.');
        },
    };
}

/** This bundle DOES read a locally stored ATS credential. */
export const FIXTURE_CREDS_SUPPORTED = true;
