/**
 * A complete fake candidate, for test builds only.
 *
 * Testing the apply agent used to require the whole upstream chain: sign into
 * the web app, sync a profile, optimise a CV so a tailored PDF exists, then
 * launch a batch — several minutes of setup before the agent does the one thing
 * under test, and every ATS bug found that way cost the same setup again. This
 * module lets `npm run build:test` produce a bundle that seeds itself.
 *
 * A normal build never reads this file: build.mjs resolves the import to
 * fixtures/noop.js instead, so the fake candidate is absent from the production
 * bundle by construction rather than by dead-code elimination (noop.js explains
 * why that distinction turned out to matter).
 *
 * Three rules this file keeps:
 *
 *   1. It NEVER overwrites real data. Seeding fills empty storage slots only, so
 *      loading a test build over a signed-in profile changes nothing.
 *   2. Every value is recognisably fake at a glance — @example.invalid is a
 *      reserved TLD that cannot resolve, and the name says TEST. A screenshot of
 *      a form filled from here should be impossible to mistake for a real
 *      application.
 *   3. The values are the ones REAL forms demand, not a minimal stub: the gaps
 *      measured on Mondelez (postal code, notice period, GPA, work
 *      authorisation, sponsorship, expected salary) are all populated, because a
 *      fixture that leaves them blank cannot exercise the steps they block.
 */

/** Flat profile — mirrors ExtensionProfile in frontend/src/lib/extension-profile.ts. */
export const DUMMY_PROFILE = {
    fullName: 'TEST Nguyen Van A',
    firstName: 'A',
    lastName: 'TEST Nguyen Van',
    email: 'copo.agent.test@example.invalid',
    phone: '0900000001',
    dateOfBirth: '1996-01-15',
    gender: '',                        // left blank on purpose: demographic fields
    nationality: 'Vietnamese',         // must resolve to a decline option, not a value
    maritalStatus: '',
    addressProvince: 'Hà Nội',
    addressDistrict: 'Cầu Giấy',
    addressStreet: '1 Duy Tan Street',
    postalCode: '100000',
    currentTitle: 'Product Owner',
    currentLevel: 'Middle',
    yearsOfExperience: 4,
    highestDegree: 'Bachelor',
    noticePeriod: '30 days',
    workAuthorized: 'Yes',
    requiresSponsorship: 'No',
    currentSalary: '',
    currentIndustry: 'Technology',
    currentFields: 'Product Management',
    desiredLocations: 'Hà Nội, Hồ Chí Minh',
    desiredSalary: '25,000,000 - 30,000,000 VND',
    coverLetter: 'This is an automated TEST application generated by a Copo test '
        + 'build. It is not a real application from a real candidate.',
    skills: 'Product Management, Roadmapping, SQL, Figma, Agile, Data Analysis',
};

/** Structured CV — mirrors CVData in frontend/src/lib/types.ts. */
export const DUMMY_CV = {
    name: 'TEST Nguyen Van A',
    summary: 'Product Owner with 4 years building B2B SaaS. TEST DATA — not a real person.',
    desired_job_title: 'Product Owner',
    skills: ['Product Management', 'Roadmapping', 'SQL', 'Figma', 'Agile', 'Data Analysis'],
    experience: [
        {
            title: 'Product Owner',
            company: 'Example Software JSC',
            duration_months: 26,
            start_date: '03/2024',
            end_date: 'Hiện tại',
            description: 'Owned the billing product. Ran discovery, wrote specs, shipped '
                + 'fortnightly with a team of six.',
        },
        {
            title: 'Business Analyst',
            company: 'Example Consulting Co',
            duration_months: 22,
            start_date: '05/2022',
            end_date: '02/2024',
            description: 'Gathered requirements and mapped processes for ERP rollouts.',
        },
    ],
    education: [
        {
            degree: 'Marketing',
            institution: 'Example National University',
            year: '2022',
            // Required on Workday's My Experience and knowable only to the
            // candidate — the exact field that stalled a real run.
            gpa: '3.2',
        },
    ],
    projects: [],
    certifications: [{ name: 'Professional Scrum Product Owner I', issuer: 'Scrum.org', year: '2023' }],
    languages: [
        { language: 'Vietnamese', level: 'Native' },
        { language: 'English', level: 'Fluent' },
    ],
    awards: [],
    activities: [],
    contact: {
        email: 'copo.agent.test@example.invalid',
        phone: '0900000001',
        address_province: 'Hà Nội',
        address_district: 'Cầu Giấy',
        address_street: '1 Duy Tan Street',
        address_postal_code: '100000',
        linkedin: '',
        github: '',
        portfolio: '',
    },
    personal: {
        date_of_birth: '1996-01-15',
        gender: '',
        nationality: 'Vietnamese',
        marital_status: '',
    },
    employment: {
        current_title: 'Product Owner',
        current_company: 'Example Software JSC',
        current_level: 'Middle',
        current_industry: 'Technology',
        current_fields: 'Product Management',
        current_salary: '',
        years_of_experience: 4,
        highest_degree: 'Bachelor',
    },
    preferences: {
        desired_locations: 'Hà Nội, Hồ Chí Minh',
        desired_salary: '25,000,000 - 30,000,000 VND',
        notice_period: '30 days',
        work_authorized: 'Yes',
        requires_sponsorship: 'No',
    },
};

export const DUMMY_CV_FILENAME = 'TEST_CANDIDATE_DO_NOT_SUBMIT.pdf';

/**
 * The lines the generated PDF carries.
 *
 * ASCII only: the PDF below writes text in Helvetica/WinAnsi, where Vietnamese
 * diacritics come out as mojibake — which is worse than plain text for the one
 * thing this document exists to feed, an ATS résumé parser.
 */
const PDF_LINES = [
    'TEST CANDIDATE - AUTOMATED TEST DATA - DO NOT SUBMIT',
    '',
    'TEST Nguyen Van A',
    'Product Owner',
    'copo.agent.test@example.invalid | 0900000001',
    '1 Duy Tan Street, Cau Giay, Ha Noi, 100000, Vietnam',
    '',
    'SUMMARY',
    'Product Owner with 4 years building B2B SaaS. This document is synthetic',
    'test data generated by a Copo test build. It describes no real person.',
    '',
    'EXPERIENCE',
    'Product Owner - Example Software JSC (03/2024 - Present)',
    'Owned the billing product. Ran discovery, wrote specs, shipped fortnightly.',
    'Business Analyst - Example Consulting Co (05/2022 - 02/2024)',
    'Gathered requirements and mapped processes for ERP rollouts.',
    '',
    'EDUCATION',
    'Example National University - Marketing (2022) - GPA 3.2',
    '',
    'LANGUAGES',
    'Vietnamese (Native), English (Fluent)',
    '',
    'SKILLS',
    'Product Management, Roadmapping, SQL, Figma, Agile, Data Analysis',
];

/** Escape a string for a PDF literal — backslash, then the two paren delimiters. */
const pdfEscape = (s) => s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');

/**
 * Build a one-page PDF as base64.
 *
 * Generated rather than embedded so no real person's CV has to live in the repo
 * to make testing work, and so the file stays a few kB instead of bloating every
 * bundle with a base64 blob.
 *
 * The xref table stores each object's BYTE offset, so offsets are measured on
 * the bytes rather than the string: the header text is ASCII, but that is a
 * property worth not depending on silently.
 */
export function buildDummyPdfBase64() {
    const text = PDF_LINES.map(l => `(${pdfEscape(l)}) Tj T*`).join('\n');
    const stream = `BT\n/F1 10 Tf\n50 790 Td\n14 TL\n${text}\nET`;

    const objects = [
        '<< /Type /Catalog /Pages 2 0 R >>',
        '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] '
            + '/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
        '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
        `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    ];

    let pdf = '%PDF-1.4\n';
    const offsets = [];
    objects.forEach((body, i) => {
        offsets.push(pdf.length);
        pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
    });

    const xrefAt = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    for (const off of offsets) pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
    pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`
        + `startxref\n${xrefAt}\n%%EOF`;

    // btoa needs one byte per char; the PDF above is ASCII by construction, and
    // charCodeAt & 0xff would silently corrupt anything that was not.
    let bin = '';
    for (let i = 0; i < pdf.length; i++) bin += String.fromCharCode(pdf.charCodeAt(i) & 0xff);
    return btoa(bin);
}

/** The storage slots the agent reads to know who it is applying as. */
export const SEED_KEYS = ['jobfitProfile', 'jobfitCv', 'cvFileBase64', 'cvFileName'];

/**
 * Fill any empty storage slot the agent reads, and report what was filled.
 *
 * Returns the list of keys seeded so the caller can log it — a test build that
 * seeds nothing (because real data is already there) looks identical to one that
 * seeded everything, and that difference is exactly what you want to know when
 * the agent then fills a form with someone's actual name.
 */
export async function seedDummyData() {
    if (typeof chrome === 'undefined' || !chrome?.storage?.local) return [];
    const KEYS = SEED_KEYS;
    const have = await chrome.storage.local.get(KEYS);
    const patch = {};

    if (!have.jobfitProfile) patch.jobfitProfile = DUMMY_PROFILE;
    if (!have.jobfitCv) { patch.jobfitCv = DUMMY_CV; patch.jobfitCvSyncedAt = Date.now(); }
    if (!have.cvFileBase64 || !have.cvFileName) {
        patch.cvFileBase64 = buildDummyPdfBase64();
        patch.cvFileName = DUMMY_CV_FILENAME;
    }

    const seeded = Object.keys(patch).filter(k => KEYS.includes(k));
    if (seeded.length) await chrome.storage.local.set(patch);
    return seeded;
}

/**
 * Seed, then say so — loudly, once per worker wake.
 *
 * The warning matters more than it looks. A fixture build behaves exactly like a
 * real one right up until it types a stranger's name into a real employer's
 * form, so the console line is the only thing that distinguishes them before
 * that point. (The data itself is the second line of defence: the name says TEST
 * and the CV file says DO NOT SUBMIT, both of which show up in the form.)
 */
export async function initFixture() {
    try {
        const seeded = await seedDummyData();
        console.warn('[Copo] ⚠️  FIXTURE BUILD — this extension carries FAKE candidate data. '
            + 'Never use it to send a real application.'
            + (seeded.length ? ` Seeded: ${seeded.join(', ')}.` : ' Real data present; seeded nothing.'));
        if (!seeded.length) {
            console.warn('[Copo] Run copoFixture.force() in this console to REPLACE it with test data, '
                + 'or copoFixture.restore() to clear it again.');
        }
        // Exposed rather than run automatically, because the automatic version of
        // "replace whatever is there" is how a test build overwrites the profile
        // of someone who only wanted to try it. Typing the command is the consent.
        self.copoFixture = {
            /** Replace real data with the fixture. Returns the keys written. */
            force: async () => {
                await chrome.storage.local.remove(SEED_KEYS);
                const keys = await seedDummyData();
                console.warn('[Copo] fixture forced:', keys.join(', '));
                return keys;
            },
            /** Wipe the four slots so the web app can re-sync the real profile. */
            restore: async () => {
                await chrome.storage.local.remove(SEED_KEYS);
                console.warn('[Copo] fixture cleared — re-sync from the web app to restore real data.');
            },
        };
    } catch (e) {
        console.warn('[Copo] fixture seed failed:', e?.message);
    }
}
