"""Interview-prep API (``/me/interview``) — dossier cache + practice attempts.

Mounted under ``/me`` so the frontend's existing ``/api/me/[[...path]]`` proxy
forwards these with auth, no new proxy route needed. The dossier itself is
GENERATED by a Next.js AI route (free); this router only persists it. Every
endpoint depends on ``get_current_user_id`` and threads it into the repo.
"""
from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel

from app.db import interview
from app.services.auth import get_current_user_id

router = APIRouter(prefix="/me/interview", tags=["Interview"])


@router.get("/preps")
async def list_preps(user_id: str = Depends(get_current_user_id)):
    """List the user's created preps (for the interview-prep landing list)."""
    return await interview.list_preps(user_id)


@router.get("/prep")
async def get_prep(
    job_ref: str = Query(...),
    cv_hash: str = Query(...),
    user_id: str = Depends(get_current_user_id),
):
    row = await interview.get_prep(user_id, job_ref, cv_hash)
    if row is None:
        raise HTTPException(status_code=404, detail="No cached prep for this CV")
    return row


class PrepUpsert(BaseModel):
    job_ref: str
    cv_hash: str
    dossier: dict


@router.put("/prep")
async def put_prep(body: PrepUpsert, user_id: str = Depends(get_current_user_id)):
    """Cache a freshly generated dossier (idempotent per job_ref + cv_hash)."""
    return await interview.upsert_prep(user_id, body.job_ref, body.cv_hash, body.dossier)


class AttemptCreate(BaseModel):
    prep_id: str
    question_id: str
    attempt_no: int
    answer_text: Optional[str] = None
    self_reflection: Optional[str] = None
    checklist: dict = {}


@router.post("/attempts")
async def post_attempt(body: AttemptCreate, user_id: str = Depends(get_current_user_id)):
    row = await interview.add_attempt(
        user_id=user_id,
        prep_id=body.prep_id,
        question_id=body.question_id,
        attempt_no=body.attempt_no,
        answer_text=body.answer_text,
        self_reflection=body.self_reflection,
        checklist=body.checklist,
    )
    if row is None:
        raise HTTPException(status_code=404, detail="Prep not found")
    return row


@router.get("/attempts")
async def get_attempts(
    prep_id: str = Query(...),
    user_id: str = Depends(get_current_user_id),
):
    return await interview.list_attempts(user_id, prep_id)
