'use client';

import { ArrowLeft, Download, RotateCcw } from 'lucide-react';
import { useAppStore, CVData } from '@/store/useAppStore';

function generateHtml(cv: CVData): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; padding: 40px 48px; line-height: 1.55; font-size: 11pt; }
    h1 { font-size: 22pt; margin-bottom: 4px; color: #111; }
    h2 { font-size: 12pt; color: #2563eb; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1.5px solid #2563eb; padding-bottom: 4px; margin: 20px 0 10px; }
    .summary { color: #444; font-size: 10.5pt; margin-bottom: 10px; }
    .skills { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 8px; }
    .skill { background: #f0f4ff; border: 1px solid #d0d8f0; border-radius: 4px; padding: 2px 8px; font-size: 9pt; }
    .exp-item { margin-bottom: 14px; }
    .exp-title { font-weight: 700; font-size: 11pt; }
    .exp-meta { font-size: 9pt; color: #666; margin-bottom: 3px; }
    .exp-desc { font-size: 10pt; color: #333; white-space: pre-wrap; }
    .edu-item { margin-bottom: 8px; }
    .disclaimer { margin-top: 24px; font-size: 8pt; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 8px; }
  </style>
</head>
<body>
  <h1>${cv.name}</h1>
  <h2>Summary</h2>
  <p class="summary">${cv.summary}</p>

  <h2>Skills</h2>
  <div class="skills">${cv.skills.map(s => `<span class="skill">${s}</span>`).join('')}</div>

  <h2>Experience</h2>
  ${cv.experience.map(e => `
    <div class="exp-item">
      <div class="exp-title">${e.title} — ${e.company}</div>
      <div class="exp-meta">${e.duration_months} months</div>
      <div class="exp-desc">${e.description}</div>
    </div>
  `).join('')}

  <h2>Education</h2>
  ${cv.education.map(e => `
    <div class="edu-item">
      <strong>${e.degree}</strong> — ${e.institution} (${e.year})
    </div>
  `).join('')}

  ${cv.projects.length > 0 ? `
    <h2>Projects</h2>
    ${cv.projects.map(p => `
      <div class="exp-item">
        <div class="exp-title">${p.name}</div>
        <div class="exp-desc">${p.description}</div>
      </div>
    `).join('')}
  ` : ''}

  <div class="disclaimer">AI-assisted optimization · Generated by AI Job Fit Optimizer</div>
</body>
</html>`;
}

export default function StepDownload() {
    const { optimizedCv, cvData, setStep, resetAll } = useAppStore();

    const handleDownload = () => {
        const data = optimizedCv || cvData;
        if (!data) return;

        const html = generateHtml(data);
        const blob = new Blob([html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${data.name.replace(/\s+/g, '_')}_optimized_cv.html`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="animate-fade-in" style={{ maxWidth: 600, margin: '0 auto', padding: '60px 20px', textAlign: 'center' }}>
            <div style={{
                width: 80,
                height: 80,
                borderRadius: '50%',
                background: 'linear-gradient(135deg, var(--accent-green), var(--accent-cyan))',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                margin: '0 auto 24px',
                boxShadow: '0 0 30px rgba(16, 185, 129, 0.3)',
            }}>
                <Download size={36} style={{ color: 'white' }} />
            </div>

            <h2 style={{ fontSize: '1.6rem', fontWeight: 700, marginBottom: 8 }}>
                Your Optimized CV is Ready!
            </h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: 36, fontSize: '0.95rem' }}>
                Download it as an ATS-friendly HTML file. You can open it in your browser and print to PDF.
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 12, alignItems: 'center' }}>
                <button className="btn-primary" onClick={handleDownload} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '1rem', padding: '14px 36px' }}>
                    <Download size={18} /> Download CV
                </button>
                <button className="btn-secondary" onClick={() => { resetAll(); setStep(1); }} style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 8 }}>
                    <RotateCcw size={16} /> Start New Analysis
                </button>
            </div>

            <div style={{ marginTop: 48, display: 'flex', justifyContent: 'center' }}>
                <button className="btn-secondary" onClick={() => setStep(4)} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                    <ArrowLeft size={16} /> Back to Comparison
                </button>
            </div>
        </div>
    );
}
