'use client';

import { useState, useMemo, useCallback } from 'react';
import {
    ArrowLeft, Sparkle, Warning, Briefcase,
    CheckCircle, FilePdf, CaretLeft, CaretRight,
    RocketLaunch, Lightning, CircleNotch,
} from '@phosphor-icons/react';
import { useAppStore } from '@/store/useAppStore';
import CvDocumentPreview from '@/components/CvDocumentPreview';
import ScoreRing from '@/components/ScoreRing';
import type { CVData } from '@/lib/types';

/**
 * Extension ID — Replace with your actual extension ID after first install.
 * Find it in chrome://extensions → Details → ID
 * For development, also works with the extension's reload ID.
 */
const EXTENSION_ID = '';  // Will be set by user

type AutoApplyStatus = 'idle' | 'checking' | 'sending' | 'opened' | 'error' | 'no-extension';

/** Try to get extension ID from localStorage (set by user or auto-detected) */
async function getStoredExtensionId(): Promise<string | null> {
    try {
        return localStorage.getItem('jobfit-extension-id');
    } catch {
        return null;
    }
}

/* ─── XSS-safe HTML escaping ─── */
function esc(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

/* ─── HTML generation for download ─── */
function generateHtml(cv: CVData): string {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; padding: 40px 48px; line-height: 1.55; font-size: 11pt; }
    h1 { font-size: 22pt; margin-bottom: 4px; color: #111; text-align: center; }
    h2 { font-size: 11pt; color: #1a1a1a; text-transform: uppercase; letter-spacing: 2px; border-bottom: 2px solid #222; padding-bottom: 4px; margin: 24px 0 12px; font-weight: 700; }
    .summary-box { border: 1px solid #ddd; padding: 12px 16px; margin-bottom: 12px; background: #fafafa; border-radius: 4px; }
    .summary { color: #333; font-size: 10.5pt; line-height: 1.6; }
    .skills { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 12px; }
    .skill { background: #f5f5f5; border: 1px solid #e0e0e0; border-radius: 4px; padding: 2px 8px; font-size: 9pt; }
    .timeline-row { display: grid; grid-template-columns: 150px 1fr; gap: 16px; margin-bottom: 16px; }
    .timeline-date { color: #555; font-size: 9.5pt; }
    .exp-title { font-weight: 700; font-size: 11pt; }
    .exp-company { font-weight: 700; font-size: 10pt; color: #333; margin-bottom: 4px; }
    .exp-desc { font-size: 10pt; color: #333; white-space: pre-wrap; line-height: 1.6; }
    .edu-institution { font-weight: 700; font-size: 11pt; }
    .edu-degree { font-size: 10pt; color: #444; }
    .disclaimer { margin-top: 28px; font-size: 8pt; color: #bbb; text-align: center; border-top: 1px solid #eee; padding-top: 8px; }
  </style>
</head>
<body>
  <h1>${esc(cv.name)}</h1>
  <h2>MỤC TIÊU NGHỀ NGHIỆP</h2>
  <div class="summary-box"><p class="summary">${esc(cv.summary)}</p></div>
  <h2>HỌC VẤN</h2>
  ${(cv.education || []).map(e => `
    <div class="timeline-row">
      <div class="timeline-date">${esc(e.year)}</div>
      <div>
        <div class="edu-institution">${esc(e.institution)}</div>
        <div class="edu-degree">${esc(e.degree)}</div>
      </div>
    </div>
  `).join('')}
  <h2>KỸ NĂNG</h2>
  <div class="skills">${(cv.skills || []).map(s => `<span class="skill">${esc(s)}</span>`).join('')}</div>
  <h2>KINH NGHIỆM LÀM VIỆC</h2>
  ${(cv.experience || []).map(e => `
    <div class="timeline-row">
      <div class="timeline-date">${e.duration_months} months</div>
      <div>
        <div class="exp-title">${esc(e.title)}</div>
        <div class="exp-company">${esc(e.company)}</div>
        <div class="exp-desc">${esc(e.description)}</div>
      </div>
    </div>
  `).join('')}
  ${(cv.projects || []).length > 0 ? `
    <h2>DỰ ÁN</h2>
    ${cv.projects.map(p => `
      <div style="margin-bottom: 14px;">
        <div class="exp-title">${esc(p.name)}</div>
        <div class="exp-desc">${esc(p.description)}</div>
      </div>
    `).join('')}
  ` : ''}
  <div class="disclaimer">AI-assisted optimization · Generated by JobFit AI</div>
</body>
</html>`;
}


/* ═══════════════════════════════════════════════════════════════════════════════
   MAIN: StepEditCv — Tab-based CV Viewer
   CV always visible, jobs as switchable tabs
   ═══════════════════════════════════════════════════════════════════════════════ */

export default function StepEditCv() {
    const { cvData, jdEntries, setStep } = useAppStore();

    // All entries that have optimized CVs, sorted by score
    const sortedEntries = useMemo(() => {
        return [...jdEntries]
            .filter(e => e.optimizedCv)
            .sort((a, b) => (b.matchResult?.overall_score ?? 0) - (a.matchResult?.overall_score ?? 0));
    }, [jdEntries]);

    const [selectedIdx, setSelectedIdx] = useState(0);
    const [autoApplyStatus, setAutoApplyStatus] = useState<AutoApplyStatus>('idle');
    const [autoApplyMessage, setAutoApplyMessage] = useState('');

    // Empty state
    if (!cvData || sortedEntries.length === 0) {
        return (
            <div className="animate-fade-in" style={{ maxWidth: 600, margin: '0 auto', padding: '60px 20px', textAlign: 'center' }}>
                <div style={{
                    width: 72, height: 72, borderRadius: 20,
                    background: 'var(--gradient-hero-subtle)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    margin: '0 auto 24px',
                    border: '1px solid var(--border-subtle)',
                }}>
                    <FilePdf size={28} weight="duotone" style={{ color: 'var(--accent-blue)' }} />
                </div>
                <h3 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: 8 }}>
                    No Optimized CVs Yet
                </h3>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginBottom: 24, lineHeight: 1.6 }}>
                    Go back to the Report page and click &quot;Optimize&quot; on jobs you&apos;re interested in.
                </p>
                <button className="btn-secondary" onClick={() => setStep(3)} style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                    <ArrowLeft size={16} /> Back to Report
                </button>
            </div>
        );
    }

    const currentEntry = sortedEntries[selectedIdx];
    const score = currentEntry?.matchResult?.overall_score ?? 0;

    const handleDownload = (editedCv: CVData) => {
        const html = generateHtml(editedCv);
        const blob = new Blob([html], { type: 'text/html' });
        const urlObj = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = urlObj;
        a.download = `${editedCv.name.replace(/\s+/g, '_')}_${(currentEntry.jobTitle || 'optimized').replace(/\s+/g, '_')}.html`;
        a.click();
        URL.revokeObjectURL(urlObj);
    };

    /* ─── Auto Apply: send profile + job URL to extension ─── */
    const triggerAutoApply = async () => {
        const cv = currentEntry?.optimizedCv;
        const jobUrl = currentEntry?.source;
        if (!cv || !jobUrl) {
            setAutoApplyStatus('error');
            setAutoApplyMessage('Thiếu dữ liệu CV hoặc Job URL.');
            return;
        }

        // Check if this is a supported job URL
        const isSupported = jobUrl.includes('vietnamworks.com') || jobUrl.includes('topcv.vn');
        if (!isSupported) {
            setAutoApplyStatus('error');
            setAutoApplyMessage('Hiện chỉ hỗ trợ VietnamWorks và TopCV. URL này chưa được hỗ trợ.');
            setTimeout(() => setAutoApplyStatus('idle'), 4000);
            return;
        }

        // Build profile from optimized CV
        const profile = {
            fullName: cv.name || '',
            firstName: cv.name?.split(' ').pop() || '',
            lastName: cv.name?.split(' ').slice(0, -1).join(' ') || '',
            currentTitle: cv.summary || '',
            coverLetter: '',
            // Add skills as fields for the extension
            skills: cv.skills || [],
        };

        setAutoApplyStatus('checking');
        setAutoApplyMessage('Đang kiểm tra Extension...');

        try {
            // Check if chrome.runtime is available and extension is installed
            const chromeRuntime = (window as any).chrome?.runtime;
            if (!chromeRuntime?.sendMessage) {
                throw new Error('NO_EXTENSION');
            }

            // Determine extension ID — try stored or use constant
            const extId = EXTENSION_ID || await getStoredExtensionId();
            if (!extId) {
                throw new Error('NO_EXTENSION_ID');
            }

            // Step 1: Ping extension to check it's alive
            const pingResponse = await new Promise<any>((resolve, reject) => {
                chromeRuntime.sendMessage(extId, { type: 'JOBFIT_PING' }, (response: any) => {
                    if (chromeRuntime.lastError) {
                        reject(new Error('NO_EXTENSION'));
                    } else {
                        resolve(response);
                    }
                });
            });

            if (!pingResponse?.success) {
                throw new Error('NO_EXTENSION');
            }

            // Step 2: Send auto-apply command
            setAutoApplyStatus('sending');
            setAutoApplyMessage(`Đang gửi lệnh Auto Apply tới ${jobUrl.includes('topcv') ? 'TopCV' : 'VietnamWorks'}...`);

            const applyResponse = await new Promise<any>((resolve, reject) => {
                chromeRuntime.sendMessage(extId, {
                    type: 'AUTO_APPLY_START',
                    jobUrl: jobUrl,
                    profile: profile,
                }, (response: any) => {
                    if (chromeRuntime.lastError) {
                        reject(new Error(chromeRuntime.lastError.message));
                    } else {
                        resolve(response);
                    }
                });
            });

            if (applyResponse?.success) {
                setAutoApplyStatus('opened');
                setAutoApplyMessage('✅ Tab đã mở! Extension đang tự động điền form. Chuyển sang tab mới để kiểm tra.');
                setTimeout(() => setAutoApplyStatus('idle'), 6000);
            } else {
                throw new Error(applyResponse?.error || 'Unknown error');
            }
        } catch (err: any) {
            if (err.message === 'NO_EXTENSION' || err.message === 'NO_EXTENSION_ID') {
                setAutoApplyStatus('no-extension');
                setAutoApplyMessage('Extension chưa được cài đặt hoặc chưa cấu hình Extension ID.');
                // Fallback: open URL in new tab
                window.open(jobUrl, '_blank');
            } else {
                setAutoApplyStatus('error');
                setAutoApplyMessage(`Lỗi: ${err.message}`);
            }
            setTimeout(() => setAutoApplyStatus('idle'), 5000);
        }
    };

    const goPrev = () => setSelectedIdx(i => Math.max(0, i - 1));
    const goNext = () => setSelectedIdx(i => Math.min(sortedEntries.length - 1, i + 1));

    // Auto Apply button config based on status
    const autoApplyBtn = {
        idle: { label: 'Auto Apply', icon: <RocketLaunch size={14} weight="fill" />, disabled: false, bg: 'linear-gradient(135deg, #059669, #10B981)' },
        checking: { label: 'Kiểm tra...', icon: <CircleNotch size={14} className="spin" />, disabled: true, bg: 'linear-gradient(135deg, #6366f1, #818cf8)' },
        sending: { label: 'Đang gửi...', icon: <CircleNotch size={14} className="spin" />, disabled: true, bg: 'linear-gradient(135deg, #6366f1, #818cf8)' },
        opened: { label: 'Đã mở tab!', icon: <CheckCircle size={14} weight="fill" />, disabled: true, bg: 'linear-gradient(135deg, #059669, #34d399)' },
        error: { label: 'Lỗi', icon: <Warning size={14} />, disabled: true, bg: 'linear-gradient(135deg, #dc2626, #ef4444)' },
        'no-extension': { label: 'Cần Extension', icon: <Lightning size={14} />, disabled: true, bg: 'linear-gradient(135deg, #d97706, #f59e0b)' },
    }[autoApplyStatus];

    return (
        <div className="animate-fade-in" style={{ maxWidth: 1100, margin: '0 auto', padding: '40px 20px' }}>

            {/* ── Header ── */}
            <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginBottom: autoApplyStatus !== 'idle' ? 8 : 20,
            }}>
                <div>
                    <h2 style={{
                        fontSize: '1.4rem', fontWeight: 700, marginBottom: 4,
                        display: 'flex', alignItems: 'center', gap: 10,
                    }}>
                        <Sparkle size={22} weight="duotone" style={{ color: 'var(--accent-purple)' }} />
                        Optimized CVs
                    </h2>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem' }}>
                        {sortedEntries.length} CV{sortedEntries.length !== 1 ? 's' : ''} optimized — switch between jobs to view each version
                    </p>
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                    <button
                        className="btn-secondary"
                        onClick={() => setStep(3)}
                        style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.85rem' }}
                    >
                        <ArrowLeft size={14} /> Back to Results
                    </button>
                    <button
                        className="btn-secondary"
                        onClick={() => {
                            const cv = currentEntry?.optimizedCv;
                            if (!cv) return;
                            const profileData = {
                                type: 'JOBFIT_EXPORT_PROFILE',
                                profile: {
                                    fullName: cv.name || '',
                                    currentTitle: cv.summary || '',
                                    coverLetter: '',
                                },
                                cvData: cv,
                            };
                            // Try to send to extension via postMessage
                            window.postMessage(profileData, '*');
                            // Also copy to clipboard as fallback
                            navigator.clipboard.writeText(JSON.stringify(profileData.profile, null, 2))
                                .then(() => alert('✅ Profile exported! Open the extension popup and click Import.'))
                                .catch(() => alert('✅ Data sent to extension via postMessage'));
                        }}
                        style={{
                            display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.85rem',
                            background: 'linear-gradient(135deg, #4F46E5, #7C3AED)',
                            color: '#fff', border: 'none', padding: '8px 16px', borderRadius: 8,
                            cursor: 'pointer',
                        }}
                    >
                        ⚡ Export to Extension
                    </button>

                    {/* ── NEW: Auto Apply Button ── */}
                    <button
                        onClick={triggerAutoApply}
                        disabled={autoApplyBtn.disabled}
                        style={{
                            display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.85rem',
                            background: autoApplyBtn.bg,
                            color: '#fff', border: 'none', padding: '8px 18px', borderRadius: 8,
                            cursor: autoApplyBtn.disabled ? 'not-allowed' : 'pointer',
                            opacity: autoApplyBtn.disabled ? 0.85 : 1,
                            transition: 'all 0.2s ease',
                            fontWeight: 600,
                            boxShadow: autoApplyStatus === 'idle' ? '0 2px 12px rgba(5,150,105,0.3)' : 'none',
                        }}
                    >
                        {autoApplyBtn.icon} {autoApplyBtn.label}
                    </button>
                </div>
            </div>

            {/* ── Auto Apply Status Bar ── */}
            {autoApplyStatus !== 'idle' && (
                <div style={{
                    background: autoApplyStatus === 'opened'
                        ? 'rgba(16,185,129,0.1)'
                        : autoApplyStatus === 'error' || autoApplyStatus === 'no-extension'
                            ? 'rgba(239,68,68,0.1)'
                            : 'rgba(99,102,241,0.1)',
                    border: `1px solid ${autoApplyStatus === 'opened'
                        ? 'rgba(16,185,129,0.3)'
                        : autoApplyStatus === 'error' || autoApplyStatus === 'no-extension'
                            ? 'rgba(239,68,68,0.3)'
                            : 'rgba(99,102,241,0.3)'}`,
                    borderRadius: 'var(--radius-sm)',
                    padding: '10px 16px',
                    marginBottom: 16,
                    fontSize: '0.82rem',
                    color: autoApplyStatus === 'opened'
                        ? '#10b981'
                        : autoApplyStatus === 'error' || autoApplyStatus === 'no-extension'
                            ? '#ef4444'
                            : '#818cf8',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                    animation: 'fadeIn 0.2s ease',
                }}>
                    {(autoApplyStatus === 'checking' || autoApplyStatus === 'sending') && (
                        <CircleNotch size={14} className="spin" />
                    )}
                    {autoApplyStatus === 'opened' && <CheckCircle size={14} weight="fill" />}
                    {autoApplyStatus === 'error' && <Warning size={14} />}
                    {autoApplyStatus === 'no-extension' && <Lightning size={14} />}
                    <span>{autoApplyMessage}</span>
                    {autoApplyStatus === 'no-extension' && (
                        <span style={{ marginLeft: 'auto', fontSize: '0.75rem', opacity: 0.8 }}>
                            Đã mở link trong tab mới — cài Extension để auto-fill.
                        </span>
                    )}
                </div>
            )}

            {/* CSS for spin animation */}
            <style>{`
                @keyframes spin { to { transform: rotate(360deg); } }
                .spin { animation: spin 1s linear infinite; }
            `}</style>

            {/* ══════ Job Selector Tabs ══════ */}
            <div style={{
                display: 'flex', alignItems: 'center', gap: 8,
                marginBottom: 20, position: 'relative',
            }}>
                {/* Prev button */}
                {sortedEntries.length > 3 && (
                    <button
                        onClick={goPrev}
                        disabled={selectedIdx === 0}
                        style={{
                            width: 32, height: 32, borderRadius: 8,
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            background: 'var(--bg-card)', border: '1px solid var(--border-subtle)',
                            color: selectedIdx === 0 ? 'var(--text-muted)' : 'var(--text-primary)',
                            cursor: selectedIdx === 0 ? 'default' : 'pointer',
                            opacity: selectedIdx === 0 ? 0.4 : 1,
                            flexShrink: 0,
                        }}
                    >
                        <CaretLeft size={14} />
                    </button>
                )}

                {/* Tabs */}
                <div style={{
                    display: 'flex', gap: 6, flex: 1,
                    overflowX: 'auto', scrollbarWidth: 'none',
                    padding: '2px 0',
                }}>
                    {sortedEntries.map((entry, idx) => {
                        const isActive = idx === selectedIdx;
                        const entryScore = entry.matchResult?.overall_score ?? 0;
                        return (
                            <button
                                key={entry.id}
                                onClick={() => setSelectedIdx(idx)}
                                style={{
                                    display: 'flex', alignItems: 'center', gap: 10,
                                    padding: '10px 16px',
                                    borderRadius: 'var(--radius-md)',
                                    border: isActive
                                        ? '1.5px solid var(--accent-blue)'
                                        : '1px solid var(--border-subtle)',
                                    background: isActive
                                        ? 'linear-gradient(135deg, rgba(99,102,241,0.08), rgba(139,92,246,0.04))'
                                        : 'var(--bg-card)',
                                    cursor: 'pointer',
                                    color: 'var(--text-primary)',
                                    transition: 'all 0.15s ease',
                                    minWidth: 0,
                                    flexShrink: 0,
                                    whiteSpace: 'nowrap',
                                    boxShadow: isActive ? '0 0 12px rgba(99,102,241,0.12)' : 'none',
                                }}
                            >
                                {/* Mini score */}
                                <ScoreRing score={entryScore} size={32} label="" />

                                <div style={{ textAlign: 'left', minWidth: 0 }}>
                                    <p style={{
                                        fontWeight: isActive ? 600 : 500,
                                        fontSize: '0.82rem',
                                        overflow: 'hidden', textOverflow: 'ellipsis',
                                        maxWidth: 180,
                                    }}>
                                        {entry.jobTitle || 'Unknown Position'}
                                    </p>
                                    <p style={{
                                        fontSize: '0.7rem',
                                        color: 'var(--text-muted)',
                                        overflow: 'hidden', textOverflow: 'ellipsis',
                                    }}>
                                        {entry.company || entry.label}
                                    </p>
                                </div>

                                {isActive && (
                                    <div style={{
                                        width: 6, height: 6, borderRadius: '50%',
                                        background: 'var(--accent-blue)',
                                        flexShrink: 0,
                                    }} />
                                )}
                            </button>
                        );
                    })}
                </div>

                {/* Next button */}
                {sortedEntries.length > 3 && (
                    <button
                        onClick={goNext}
                        disabled={selectedIdx === sortedEntries.length - 1}
                        style={{
                            width: 32, height: 32, borderRadius: 8,
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            background: 'var(--bg-card)', border: '1px solid var(--border-subtle)',
                            color: selectedIdx === sortedEntries.length - 1 ? 'var(--text-muted)' : 'var(--text-primary)',
                            cursor: selectedIdx === sortedEntries.length - 1 ? 'default' : 'pointer',
                            opacity: selectedIdx === sortedEntries.length - 1 ? 0.4 : 1,
                            flexShrink: 0,
                        }}
                    >
                        <CaretRight size={14} />
                    </button>
                )}
            </div>

            {/* ══════ Current Job Context Card ══════ */}
            <div className="glass-card" style={{
                padding: '14px 20px', marginBottom: 16,
                display: 'flex', alignItems: 'center', gap: 16,
                background: 'linear-gradient(135deg, rgba(59,130,246,0.05), rgba(139,92,246,0.03))',
            }}>
                <ScoreRing score={score} size={48} label="" />
                <div style={{ flex: 1, minWidth: 0 }}>
                    <p style={{ fontWeight: 600, fontSize: '0.95rem', marginBottom: 2 }}>
                        {currentEntry.jobTitle || 'Unknown Position'}
                    </p>
                    <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: 6 }}>
                        {currentEntry.company && (
                            <span style={{ display: 'flex', alignItems: 'center', gap: 3 }}>
                                <Briefcase size={11} /> {currentEntry.company}
                            </span>
                        )}
                        {currentEntry.company && <span style={{ opacity: 0.4 }}>·</span>}
                        <span>{currentEntry.label}</span>
                    </p>
                </div>
                <div style={{ display: 'flex', gap: 6 }}>
                    {currentEntry.jdData?.domain && (
                        <span style={{
                            fontSize: '0.7rem', padding: '3px 10px', borderRadius: 12,
                            background: 'rgba(59,130,246,0.1)', color: 'var(--accent-blue)',
                        }}>{currentEntry.jdData.domain}</span>
                    )}
                    {currentEntry.jdData?.seniority_expected && (
                        <span style={{
                            fontSize: '0.7rem', padding: '3px 10px', borderRadius: 12,
                            background: 'rgba(139,92,246,0.1)', color: 'var(--accent-purple)',
                        }}>{currentEntry.jdData.seniority_expected}</span>
                    )}
                </div>
                {/* Navigation: x of y */}
                <div style={{
                    fontSize: '0.75rem', color: 'var(--text-muted)',
                    display: 'flex', alignItems: 'center', gap: 8,
                    flexShrink: 0,
                }}>
                    <button
                        onClick={goPrev}
                        disabled={selectedIdx === 0}
                        style={{
                            background: 'none', border: 'none', cursor: selectedIdx === 0 ? 'default' : 'pointer',
                            color: selectedIdx === 0 ? 'var(--text-muted)' : 'var(--accent-blue)',
                            padding: 4, display: 'flex', opacity: selectedIdx === 0 ? 0.3 : 1,
                        }}
                    >
                        <CaretLeft size={14} weight="bold" />
                    </button>
                    <span style={{ fontWeight: 600 }}>{selectedIdx + 1} / {sortedEntries.length}</span>
                    <button
                        onClick={goNext}
                        disabled={selectedIdx === sortedEntries.length - 1}
                        style={{
                            background: 'none', border: 'none',
                            cursor: selectedIdx === sortedEntries.length - 1 ? 'default' : 'pointer',
                            color: selectedIdx === sortedEntries.length - 1 ? 'var(--text-muted)' : 'var(--accent-blue)',
                            padding: 4, display: 'flex',
                            opacity: selectedIdx === sortedEntries.length - 1 ? 0.3 : 1,
                        }}
                    >
                        <CaretRight size={14} weight="bold" />
                    </button>
                </div>
            </div>

            {/* ══════ AI Disclaimer ══════ */}
            <div style={{
                background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.25)',
                borderRadius: 'var(--radius-sm)', padding: '8px 14px', marginBottom: 20,
                fontSize: '0.78rem', color: 'var(--accent-amber)',
                display: 'flex', alignItems: 'center', gap: 6,
            }}>
                <Warning size={12} />
                AI-optimized for &quot;{currentEntry.jobTitle || 'this position'}&quot; — Click any text to edit, then Save &amp; Download
            </div>

            {/* ══════ CV Document — ALWAYS VISIBLE ══════ */}
            <CvDocumentPreview
                key={currentEntry.id}
                originalCv={cvData}
                optimizedCv={currentEntry.optimizedCv!}
                onSave={handleDownload}
            />

            {/* Hide scrollbar for tabs */}
            <style>{`
                div::-webkit-scrollbar { display: none; }
            `}</style>
        </div>
    );
}
