'use client';

import { useState } from 'react';
import {
    ArrowLeft, DownloadSimple, ArrowCounterClockwise,
    Sparkle, Warning, FilePdf, Eye, EyeSlash,
} from '@phosphor-icons/react';
import { useAppStore } from '@/store/useAppStore';
import EditableCvPreview from '@/components/EditableCvPreview';
import type { CVData } from '@/lib/types';
import ScoreRing from '@/components/ScoreRing';

/* ─── XSS-safe HTML escaping ─── */
function esc(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

/* ─── HTML generation for download ─── */
function generateHtml(cv: CVData): string {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; padding: 40px 48px; line-height: 1.55; font-size: 11pt; }
    h1 { font-size: 22pt; margin-bottom: 4px; color: #111; }
    h2 { font-size: 12pt; color: #2563eb; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1.5px solid #2563eb; padding-bottom: 4px; margin: 20px 0 10px; }
    .summary { color: #444; font-size: 10.5pt; margin-bottom: 10px; }
    .skills { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 8px; }
    .skill { background: #f0f4ff; border: 1px solid #d0d8f0; border-radius: 4px; padding: 2px 8px; font-size: 9pt; }
    .exp-item { margin-bottom: 14px; }
    .exp-title { font-weight: 700; font-size: 11pt; }
    .exp-meta { font-size: 9pt; color: #666; margin-bottom: 3px; }
    .exp-desc { font-size: 10pt; color: #333; white-space: pre-wrap; }
    .edu-item { margin-bottom: 8px; }
    .disclaimer { margin-top: 24px; font-size: 8pt; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 8px; }
  </style>
</head>
<body>
  <h1>${esc(cv.name)}</h1>
  <h2>Summary</h2>
  <p class="summary">${esc(cv.summary)}</p>
  <h2>Skills</h2>
  <div class="skills">${(cv.skills || []).map(s => `<span class="skill">${esc(s)}</span>`).join('')}</div>
  <h2>Experience</h2>
  ${(cv.experience || []).map(e => `
    <div class="exp-item">
      <div class="exp-title">${esc(e.title)} — ${esc(e.company)}</div>
      <div class="exp-meta">${e.duration_months} months</div>
      <div class="exp-desc">${esc(e.description)}</div>
    </div>
  `).join('')}
  <h2>Education</h2>
  ${(cv.education || []).map(e => `
    <div class="edu-item">
      <strong>${esc(e.degree)}</strong> — ${esc(e.institution)} (${esc(e.year)})
    </div>
  `).join('')}
  ${(cv.projects || []).length > 0 ? `
    <h2>Projects</h2>
    ${cv.projects.map(p => `
      <div class="exp-item">
        <div class="exp-title">${esc(p.name)}</div>
        <div class="exp-desc">${esc(p.description)}</div>
      </div>
    `).join('')}
  ` : ''}
  <div class="disclaimer">AI-assisted optimization · Generated by AI Job Fit Optimizer</div>
</body>
</html>`;
}

export default function StepEditCv() {
    const {
        cvData, jdEntries, selectedJdId, setStep, updateJdEntry,
    } = useAppStore();

    const [showPreview, setShowPreview] = useState(false);

    // Find the selected entry
    const entry = jdEntries.find(e => e.id === selectedJdId);

    if (!cvData || !entry || !entry.optimizedCv) {
        return (
            <div className="animate-fade-in" style={{ maxWidth: 600, margin: '0 auto', padding: '60px 20px', textAlign: 'center' }}>
                <p style={{ color: 'var(--text-secondary)' }}>
                    No optimized CV found. Go back to the report and optimize a job first.
                </p>
                <button className="btn-secondary" onClick={() => setStep(3)} style={{ marginTop: 20, display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                    <ArrowLeft size={16} /> Back to Report
                </button>
            </div>
        );
    }

    const m = entry.matchResult;
    const jd = entry.jdData;

    const handleDownload = (editedCv: CVData) => {
        const html = generateHtml(editedCv);
        const blob = new Blob([html], { type: 'text/html' });
        const urlObj = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = urlObj;
        a.download = `${editedCv.name.replace(/\s+/g, '_')}_optimized.html`;
        a.click();
        URL.revokeObjectURL(urlObj);
    };

    return (
        <div className="animate-fade-in" style={{ maxWidth: 1100, margin: '0 auto', padding: '40px 20px' }}>

            {/* ── Header Bar ── */}
            <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginBottom: 24,
            }}>
                <div>
                    <h2 style={{ fontSize: '1.4rem', fontWeight: 700, marginBottom: 4, display: 'flex', alignItems: 'center', gap: 10 }}>
                        <Sparkle size={22} weight="duotone" style={{ color: 'var(--accent-purple)' }} />
                        Edit Optimized CV
                    </h2>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem' }}>
                        Review and edit the AI-optimized CV, then download when ready.
                    </p>
                </div>
                <button
                    className="btn-secondary"
                    onClick={() => setStep(3)}
                    style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.85rem' }}
                >
                    <ArrowLeft size={14} /> Back to Results
                </button>
            </div>

            {/* ── Job Context Card ── */}
            {m && jd && (
                <div className="glass-card" style={{
                    padding: '16px 24px', marginBottom: 24,
                    display: 'flex', alignItems: 'center', gap: 20,
                    background: 'linear-gradient(135deg, rgba(59,130,246,0.05), rgba(139,92,246,0.03))',
                }}>
                    <ScoreRing score={m.overall_score} size={56} label="" />
                    <div style={{ flex: 1, minWidth: 0 }}>
                        <p style={{ fontWeight: 600, fontSize: '0.95rem', marginBottom: 2 }}>
                            {entry.jobTitle || 'Unknown Position'}
                        </p>
                        <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                            {entry.company && `${entry.company} · `}{entry.label}
                        </p>
                    </div>
                    <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                        {jd.domain && (
                            <span style={{
                                fontSize: '0.7rem', padding: '3px 10px', borderRadius: 12,
                                background: 'rgba(59,130,246,0.1)', color: 'var(--accent-blue)',
                            }}>{jd.domain}</span>
                        )}
                        {jd.seniority_expected && (
                            <span style={{
                                fontSize: '0.7rem', padding: '3px 10px', borderRadius: 12,
                                background: 'rgba(139,92,246,0.1)', color: 'var(--accent-purple)',
                            }}>{jd.seniority_expected}</span>
                        )}
                    </div>
                </div>
            )}

            {/* ── Disclaimer ── */}
            <div style={{
                background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.25)',
                borderRadius: 'var(--radius-md)', padding: '10px 16px', marginBottom: 20,
                fontSize: '0.82rem', color: 'var(--accent-amber)',
                display: 'flex', alignItems: 'center', gap: 6,
            }}>
                <Warning size={14} />
                AI-assisted optimization · Edit any section below, then click &ldquo;Save &amp; Download&rdquo;
            </div>

            {/* ── Editable CV Preview ── */}
            <EditableCvPreview
                originalCv={cvData}
                optimizedCv={entry.optimizedCv}
                onSave={handleDownload}
            />
        </div>
    );
}
