import type { CVData } from './types';

/* ─── XSS-safe HTML escaping ─── */
export function escapeHtml(str: string): string {
    return (str ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

/* ─── Render a description string (newline-separated bullets) into HTML ─── */
function bulletsToHtml(text: string): string {
    if (!text) return '';
    const lines = text
        .split('\n')
        .map((l) => l.replace(/^\s*[-*•]\s*/, '').trim())
        .filter(Boolean);
    if (lines.length === 0) return '';
    if (lines.length === 1) return `<p class="single-line">${escapeHtml(lines[0])}</p>`;
    return `<ul class="bullets">${lines.map((l) => `<li>${escapeHtml(l)}</li>`).join('')}</ul>`;
}

/* ─── Generate a complete printable HTML document from a CVData object ─── */
export function generateCvHtml(cv: CVData): string {
    return `<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(cv.name || 'CV')}</title>
  <style>
    @page { size: A4; margin: 15mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      color: #1a1a2e;
      line-height: 1.55;
      font-size: 11pt;
    }
    h1 {
      font-size: 22pt;
      margin-bottom: 4px;
      color: #111;
      text-align: center;
      letter-spacing: -0.5px;
    }
    h2 {
      font-size: 11pt;
      color: #1a1a1a;
      text-transform: uppercase;
      letter-spacing: 2px;
      border-bottom: 2px solid #222;
      padding-bottom: 4px;
      margin: 24px 0 12px;
      font-weight: 700;
    }
    .summary-box {
      border: 1px solid #ddd;
      padding: 12px 16px;
      margin-bottom: 12px;
      background: #fafafa;
      border-radius: 4px;
    }
    .summary { color: #333; font-size: 10.5pt; line-height: 1.6; }
    .skills { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 12px; }
    .skill {
      background: #f5f5f5;
      border: 1px solid #e0e0e0;
      border-radius: 4px;
      padding: 2px 8px;
      font-size: 9pt;
    }
    .timeline-row {
      display: grid;
      grid-template-columns: 150px 1fr;
      gap: 16px;
      margin-bottom: 16px;
      page-break-inside: avoid;
    }
    .timeline-date { color: #555; font-size: 9.5pt; }
    .exp-title { font-weight: 700; font-size: 11pt; }
    .exp-company { font-weight: 700; font-size: 10pt; color: #333; margin-bottom: 4px; }
    .exp-desc { font-size: 10pt; color: #333; line-height: 1.55; }
    .exp-desc ul.bullets { padding-left: 18px; margin: 4px 0; }
    .exp-desc ul.bullets li { margin: 3px 0; }
    .exp-desc p.single-line { white-space: pre-wrap; }
    .edu-institution { font-weight: 700; font-size: 11pt; }
    .edu-degree { font-size: 10pt; color: #444; }
    .project-block { margin-bottom: 14px; page-break-inside: avoid; }
    .project-name { font-weight: 700; font-size: 11pt; margin-bottom: 4px; }
    .project-desc ul.bullets { padding-left: 18px; margin: 4px 0; }
    .project-desc ul.bullets li { margin: 3px 0; }
    .project-desc p.single-line { white-space: pre-wrap; }
    .disclaimer {
      margin-top: 28px;
      font-size: 8pt;
      color: #bbb;
      text-align: center;
      border-top: 1px solid #eee;
      padding-top: 8px;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(cv.name)}</h1>

  <h2>MỤC TIÊU NGHỀ NGHIỆP</h2>
  <div class="summary-box"><p class="summary">${escapeHtml(cv.summary)}</p></div>

  <h2>HỌC VẤN</h2>
  ${(cv.education || []).map((e) => `
    <div class="timeline-row">
      <div class="timeline-date">${escapeHtml(e.year)}</div>
      <div>
        <div class="edu-institution">${escapeHtml(e.institution)}</div>
        <div class="edu-degree">${escapeHtml(e.degree)}</div>
      </div>
    </div>
  `).join('')}

  <h2>KỸ NĂNG</h2>
  <div class="skills">${(cv.skills || []).map((s) => `<span class="skill">${escapeHtml(s)}</span>`).join('')}</div>

  <h2>KINH NGHIỆM LÀM VIỆC</h2>
  ${(cv.experience || []).map((e) => `
    <div class="timeline-row">
      <div class="timeline-date">${escapeHtml(String(e.duration_months ?? 0))} months</div>
      <div>
        <div class="exp-title">${escapeHtml(e.title)}</div>
        <div class="exp-company">${escapeHtml(e.company)}</div>
        <div class="exp-desc">${bulletsToHtml(e.description)}</div>
      </div>
    </div>
  `).join('')}

  ${(cv.projects || []).length > 0 ? `
    <h2>DỰ ÁN</h2>
    ${cv.projects.map((p) => `
      <div class="project-block">
        <div class="project-name">${escapeHtml(p.name)}</div>
        <div class="project-desc">${bulletsToHtml(p.description)}</div>
      </div>
    `).join('')}
  ` : ''}

  <div class="disclaimer">AI-assisted optimization · Generated by JobFit AI</div>
</body>
</html>`;
}

/* ─── Suggested filename, sanitized for download ─── */
export function buildCvFileName(cv: CVData, jobTitle?: string): string {
    const name = (cv.name || 'cv').replace(/[^A-Za-z0-9_\- ]/g, '').trim().replace(/\s+/g, '_');
    const job = (jobTitle || 'optimized').replace(/[^A-Za-z0-9_\- ]/g, '').trim().replace(/\s+/g, '_');
    return `${name || 'cv'}_${job || 'optimized'}`.slice(0, 80);
}
