// The Workday Field of Study catalogue, measured off the live MDLZ form (327
// majors, English, closed set — R-172558 / R-173704, 2026-08-10/11). Field of
// study is a SINGLE-select closed list with no free text, so a value that is
// not one of these is refused: a Vietnamese major, or an English one the list
// does not carry, must be resolved to the nearest label here BEFORE it reaches
// the extension. Verbatim (incl. the "Soil ScienceTurfgrass Science" quirk) —
// do not tidy.

export const FIELD_OF_STUDY_CATALOG: readonly string[] = [
    "Accounting",
    "Actuarial Science",
    "Advertising",
    "Aerospace Engineering",
    "African-American Studies",
    "African Languages, Literatures, and Linguistics",
    "African Studies",
    "Agricultural/Biological Engineering and Bioengineering",
    "Agricultural Business and Management",
    "Agricultural Economics",
    "Agricultural Education",
    "Agricultural Journalism",
    "Agricultural Mechanization",
    "Agricultural Technology Management",
    "Agriculture",
    "Agronomy and Crop Science",
    "Air Traffic Control",
    "American History",
    "American Literature",
    "American Sign Language",
    "American Studies",
    "Anatomy",
    "Ancient Studies",
    "Animal Behavior and Ethology",
    "Animal Science",
    "Animation and Special Effects",
    "Anthropology",
    "Applied Mathematics",
    "Applied Physics",
    "Aquaculture",
    "Aquatic Biology",
    "Arabic",
    "Archeology",
    "Architectural Engineering",
    "Architectural History",
    "Architecture",
    "Art",
    "Art Education",
    "Art History",
    "Artificial Intelligence and Robotics",
    "Art Therapy",
    "Asian-American Studies",
    "Astronomy",
    "Astrophysics",
    "Athletic Training",
    "Atmospheric Science",
    "Automotive Engineering",
    "Aviation",
    "Bakery Science",
    "Biblical Studies",
    "Biochemistry",
    "Bioethics",
    "Biology",
    "Biomedical Engineering",
    "Biomedical Science",
    "Biopsychology",
    "Biotechnology",
    "Botany/Plant Biology",
    "Business Administration",
    "Business Administration/Management",
    "Business Communications",
    "Business Education",
    "Canadian Studies",
    "Caribbean Studies",
    "Cell Biology",
    "Ceramic Engineering",
    "Ceramics",
    "Chemical Engineering",
    "Chemical Physics",
    "Chemistry",
    "Child Care",
    "Child Development",
    "Chinese",
    "Chiropractic",
    "Church Music",
    "Cinematography and Film/Video Production",
    "Circulation Technology",
    "Civil Engineering",
    "Classics",
    "Clinical Psychology",
    "Cognitive Psychology",
    "Communication Disorders",
    "Communications Studies/Speech Communication and Rhetoric",
    "Comparative Literature",
    "Computer and Information Science",
    "Computer Engineering",
    "Computer Graphics",
    "Computer Systems Analysis",
    "Construction Management",
    "Counseling",
    "Crafts",
    "Creative Writing",
    "Criminal Science",
    "Criminology",
    "Culinary Arts",
    "Dance",
    "Data Processing",
    "Data Science",
    "Dental Hygiene",
    "Developmental Psychology",
    "Diagnostic Medical Sonography",
    "Dietetics",
    "Digital Communications and Media/Multimedia",
    "Drawing",
    "Early Childhood Education",
    "East Asian Studies",
    "East European Studies",
    "Ecology",
    "Economics",
    "Education",
    "Education Administration",
    "Educational Psychology",
    "Education of the Deaf",
    "Electrical Engineering",
    "Electrician",
    "Elementary Education",
    "Engineering",
    "Engineering Mechanics",
    "Engineering Physics",
    "English",
    "English Composition",
    "English Literature",
    "Entomology",
    "Entrepreneurship",
    "Environmental/Environmental Health Engineering",
    "Environmental Design/Architecture",
    "Environmental Science",
    "Epidemiology",
    "Equine Studies",
    "Ethnic Studies",
    "European History",
    "Experimental Pathology",
    "Experimental Psychology",
    "Fashion Design",
    "Fashion Merchandising",
    "Feed Science",
    "Fiber, Textiles, and Weaving Arts",
    "Film",
    "Finance",
    "Floriculture",
    "Food Science",
    "Forensic Science",
    "Forestry",
    "French",
    "Furniture Design",
    "Game Design",
    "Gay and Lesbian Studies",
    "Genetics",
    "Geography",
    "Geological Engineering",
    "Geology",
    "Geophysics",
    "German",
    "Gerontology",
    "Government",
    "Graphic Design",
    "Health Administration",
    "Hebrew",
    "Hispanic-American, Puerto Rican, and Chicano Studies",
    "Historic Preservation",
    "History",
    "Home Economics",
    "Horticulture",
    "Hospitality",
    "Human Development",
    "Humanities",
    "Human Resources Management",
    "Illustration",
    "Industrial Design",
    "Industrial Engineering",
    "Industrial Management",
    "Industrial Psychology",
    "Information Technology",
    "Interior Architecture",
    "Interior Design",
    "International Agriculture",
    "International Business",
    "International Relations",
    "International Studies",
    "Islamic Studies",
    "Italian",
    "Japanese",
    "Jazz Studies",
    "Jewelry and Metalsmithing",
    "Jewish Studies",
    "Journalism",
    "Kinesiology",
    "Korean",
    "Landscape Architecture",
    "Landscape Horticulture",
    "Land Use Planning and Management",
    "Latin American Studies",
    "Law",
    "Library Science",
    "Linguistics",
    "Logistics Management",
    "Management Information Systems",
    "Managerial Economics",
    "Marine Biology",
    "Marine Science",
    "Marketing",
    "Massage Therapy",
    "Mass Communication",
    "Materials Science",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Technology",
    "Medicine",
    "Medieval and Renaissance Studies",
    "Mental Health Services",
    "Merchandising and Buying Operations",
    "Metallurgical Engineering",
    "Microbiology",
    "Middle Eastern Studies",
    "Military Science",
    "Mineral Engineering",
    "Missions",
    "Modern Greek",
    "Molecular Biology",
    "Molecular Genetics",
    "Mortuary Science",
    "Museum Studies",
    "Music",
    "Musical Theater",
    "Music Education",
    "Music History",
    "Music Management",
    "Music Therapy",
    "Native American Studies",
    "Natural Resources Conservation",
    "Naval Architecture",
    "Neurobiology",
    "Neuroscience",
    "Nuclear Engineering",
    "Nursing",
    "Nutrition",
    "Occupational Therapy",
    "Ocean Engineering",
    "Oceanography",
    "Office Administration",
    "Operations Management",
    "Organizational Behavior Studies",
    "Painting",
    "Paleontology",
    "Pastoral Studies",
    "Peace Studies",
    "Petroleum Engineering",
    "Pharmacology",
    "Pharmacy",
    "Philosophy",
    "Photography",
    "Photojournalism",
    "Physical Education",
    "Physical Therapy",
    "Physician Assistant",
    "Physics",
    "Physiological Psychology",
    "Piano",
    "Planetary Science",
    "Plant Pathology",
    "Playwriting and Screenwriting",
    "Political Communication",
    "Political Science",
    "Portuguese",
    "Pre-Dentistry",
    "Pre-Law",
    "Pre-Medicine",
    "Pre-Optometry",
    "Pre-Seminary",
    "Pre-Veterinary Medicine",
    "Printmaking",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Public Policy Analysis",
    "Public Relations",
    "Radio and Television",
    "Radiologic Technology",
    "Range Science and Management",
    "Real Estate",
    "Recording Arts Technology",
    "Recreation Management",
    "Rehabilitation Services",
    "Religious Studies",
    "Respiratory Therapy",
    "Risk Management",
    "Rural Sociology",
    "Russian",
    "Scandinavian Studies",
    "Sculpture",
    "Skilled Trades",
    "Slavic Languages and Literatures",
    "Social Psychology",
    "Social Work",
    "Sociology",
    "Soil ScienceTurfgrass Science",
    "Sound Engineering",
    "South Asian Studies",
    "Southeast Asia Studies",
    "Spanish",
    "Special Education",
    "Speech Pathology",
    "Sport and Leisure Studies",
    "Sports Management",
    "Statistics",
    "Surveying",
    "Sustainable Resource Management",
    "Teacher Education",
    "Teaching English as a Second Language",
    "Technical Writing",
    "Technology Education",
    "Textile Engineering",
    "Theatre",
    "Theology",
    "Tourism",
    "Toxicology",
    "Urban Planning",
    "Urban Studies",
    "Visual Communication",
    "Voice",
    "Web Design",
    "Webmaster and Web Management",
    "Welding Engineering",
    "Wildlife Management",
    "Women's Studies",
    "Youth Ministries",
    "Zoology",
];
